// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAOpg8G-cyxVXzSAD0E9OdaOkSfr0ukNWs',
//     appId: '1:31625922511:web:7bfbd8a51eaa10da45f4ba',
//     messagingSenderId: '31625922511',
//     projectId: 'nguyenthongoc-a046c',
//     authDomain: 'nguyenthongoc-a046c.firebaseapp.com',
//     storageBucket: 'nguyenthongoc-a046c.firebasestorage.app',
//     measurementId: 'G-76MBYD5PG0',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAgWNKnuV6Kf5X5QaHeFDcu1rCrRr-XCUU',
//     appId: '1:31625922511:android:5d4a45d574bfee0845f4ba',
//     messagingSenderId: '31625922511',
//     projectId: 'nguyenthongoc-a046c',
//     storageBucket: 'nguyenthongoc-a046c.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC5APrJUtshI-eyKjd9xk9xSfPK3spGCLU',
//     appId: '1:31625922511:ios:0d0968bd0157930245f4ba',
//     messagingSenderId: '31625922511',
//     projectId: 'nguyenthongoc-a046c',
//     storageBucket: 'nguyenthongoc-a046c.firebasestorage.app',
//     iosBundleId: 'com.example.spotify',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC5APrJUtshI-eyKjd9xk9xSfPK3spGCLU',
//     appId: '1:31625922511:ios:0d0968bd0157930245f4ba',
//     messagingSenderId: '31625922511',
//     projectId: 'nguyenthongoc-a046c',
//     storageBucket: 'nguyenthongoc-a046c.firebasestorage.app',
//     iosBundleId: 'com.example.spotify',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAOpg8G-cyxVXzSAD0E9OdaOkSfr0ukNWs',
//     appId: '1:31625922511:web:ce28e8d6f91b889845f4ba',
//     messagingSenderId: '31625922511',
//     projectId: 'nguyenthongoc-a046c',
//     authDomain: 'nguyenthongoc-a046c.firebaseapp.com',
//     storageBucket: 'nguyenthongoc-a046c.firebasestorage.app',
//     measurementId: 'G-SKSWX093ZB',
//   );

// }
